"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Weapon_1 = require("./Weapon");
const Spell_1 = require("./Spell");
const Mage_1 = require("./Mage");
const Warrior_1 = require("./Warrior");
const Party_1 = require("./Party");
let weapon1 = new Weapon_1.Weapon('Espada Matadoraaaa', 35);
let weapon2 = new Weapon_1.Weapon('Granada assasina', 43);
let spell1 = new Spell_1.Spell('Estacas de geloooo', 37, 28);
let spell2 = new Spell_1.Spell('Bola de fogoooo', 41, 35);
let warrior1 = new Warrior_1.Warrior('Crimson Knight', 100, weapon1);
let warrior2 = new Warrior_1.Warrior('Superior warrior', 150, weapon2);
let mage1 = new Mage_1.Mage('Ice Queen', 180, spell1);
let mage2 = new Mage_1.Mage('Skull Lord', 150, spell2);
let party1 = new Party_1.Party('Explosive snap-pops');
party1.addMember(warrior1);
party1.addMember(warrior2);
party1.addMember(mage1);
party1.addMember(mage2);
party1.showMembers();
warrior1.showInfo();
warrior2.showInfo();
mage1.showInfo();
mage2.showInfo();
warrior1.attack();
warrior2.attack();
mage1.castSpell();
mage2.castSpell();
mage2.castSpell();
mage2.castSpell();
mage2.castSpell();
mage2.castSpell();
console.log(warrior1.takeDatakeDamage(30));
